#!/usr/bin/env ruby
# encoding: UTF-8

$LOAD_PATH << './lib'

require 'smallq/client'
require 'smallq/config'

def stats(c)
  l = {}
  c.stats.each do |q|
    l[q[:queue_name]] = q
  end
  l
end

filename = ARGV[0]

config = Smallq::Config.load(filename)

c = Smallq::Client.new(config['server'])

a = stats(c)
old_a = {}
now = nil
old_now = nil

loop do
  now = Time.now

  if a.any?
    max = a.keys.map(&:size).max
    max = 8 if max < 8

    puts "%-#{max}s |       adds |       gets |       size |        TPS" % now.strftime('%H:%M:%S')
    puts "#{'-' * max}-+------------+------------+------------+-----------"
    a.each do |q, data|
      if old_now.nil? || old_a[q].nil?
        puts "%-#{max}s | %10d | %10d | %10d |          -" % [q, data[:adds], data[:gets], data[:size]]
      else
        diff = now - old_now
        total = (data[:adds] - old_a[q][:adds]) + (data[:gets] - old_a[q][:gets])
        puts "%-#{max}s | %10d | %10d | %10d | %10.2f" % [q, data[:adds], data[:gets], data[:size], total.to_f / diff]
      end
    end
  else
    puts 'No currently active queues'
  end

  puts
  
  sleep 5
  old_a = a
  a = stats(c)

  old_now = now
end
