#!/usr/bin/env ruby

$LOAD_PATH << './lib'

require 'smallq/client'
require 'smallq/config'

TRUE = %w(true y yes 1).freeze

filename = ARGV[0]

config = Smallq::Config.load(filename)

queue_name = ARGV[1]

forever = TRUE.includes?(ARGV[2])

client = Smallq::Client.new(config['server'])

if forever
  puts "Draining queue [#{queue_name}] forever"
else
  puts "Draining queue [#{queue_name}] until empty"
end

loop do
  x = client.get(queue_name)

  until x[:status] == 'ERROR'
    x = client.get(queue_name)
  end

  break unless forever == true
  sleep 5
end
